name: Android CI - Construir APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Construir APK (debug)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Android SDK
        uses: android-actions/setup-android@v3

      - name: Permitir execução do Gradle
        run: chmod +x ./gradlew

      - name: Construir APK (debug)
        run: ./gradlew assembleDebug

      - name: Salvar artefato (APK gerado)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: |
            app/build/outputs/apk/debug/app-debug.apk
